### PR TITLE
DPIv2: Video Plots + Tasks 

### PR DESCRIPTION
**Pull request by ktiwary2**
Incredible apologies for the delay, but this should be all the necessary plots + constants for the video part of the paper. Let me know if other analyses are needed. I will PR the multimodal_analysis stuff sepertely/or add it here. 

### How to Review: 

It's arranged by commits so I would look at those instead of the files directly. 

1. **Video plots** are in [here](https://github.com/Data-Provenance-Initiative/Data-Provenance-Collection/pull/179/commits/1984e578033fbdb4e4a36424e3e3076a9b2bcae4) 
2. **Constants**: [here](https://github.com/Data-Provenance-Initiative/Data-Provenance-Collection/pull/179/commits/dbb56fdb71ea998b825ebdfadf53f7f13bcf9bb6)
3. **Task Summaries**: won't be too useful to look at cause there are > 100 jsons but [incase](https://github.com/Data-Provenance-Initiative/Data-Provenance-Collection/pull/179/commits/2fb835ea83d36e6462e141419675c8bda272d126)

### CODE REVIEW

**Comment by shayne-longpre** [comment]
@ktiwary2 great start! A couple minor things:
* You'll notice that in re-generating the data summaries you deleted the inferrred metadata and bibtex info that we had generated for each one. Could you make sure to add your new metadata without deleting those parts?
* We would like all plots to be generated through multimodal_analysis.ipynb, rather than duplicated code in its own notebook. When we are generating the same or concatenated figures for all 3 modalities we need to have the same code responsible for those, so we don't need to make the changes in multiple places. Could you merge it into multimodal_analysis, so we are using the same pipelines?
* Ideally we should be building out multimodal_analysis, not adding too much stuff to it. Wherever possible please edit or add any code to multimodal_util, so that the analysis notebook is simply calling the data processing and plotting functions.

**Comment by ktiwary2** [comment]
Instead of rebasing, I pulled and that's why there are so many commits here. I will fix this so that the PR is self contained. 

In the mean time let me know what the feedback is on the following notebooks:  `multimodal_analysis.ipynb` and from `video_analysis.ipynb`. 
Link to the multimodal and video specific plots: https://drive.google.com/drive/folders/1LUf4SRD53QLH8VmpnZX--K2Lwe5AOs00?usp=sharing

**Comment by ktiwary2** [comment]
creator_categories_by_modality
dataset_count_by_continent_and_modality
dataset_count_by_country_and_modality
license_use_by_modality_collections
multimodal-combined_chart
source_categories_by_modality-aggregated
source_categories_by_modality

**Comment by ktiwary2** [comment]
video_creatorcategories-years
video_sourcecategories-cumulativehours
video_sourcecategories-years
video_sourcecategories-yearscombined
video_sources-licenses
video_taskcategories-years

**Comment by ktiwary2** [comment]
Closing this; please see https://github.com/Data-Provenance-Initiative/Data-Provenance-Collection/pull/181 which resolves the issues above + the comments.

**Pull request closed without merging**
